orbs: 
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-s3: circleci/aws-s3@1.0.0
  browser: circleci/browser-tools@1.2.4
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install
      - aws-cli/setup
      - eb/setup
      - browser/install-chrome
      - browser/install-chromedriver
      - run:
          name: install independencies for frontend
          command: npm run install:frontend
      - run:
          name: install independencies for server
          command: npm run install:server
      - run:
          name: build frontend folder
          command: npm run build:frontend
      - run:
          name: build backend folder
          command: npm run build:server
      - run:
          name: test frontend
          command: npm run test:frontend
      - run:
          name: frontend deployment to s3
          command: npm run deploy:s3
      - run:
          name: server deployment to eb
          command: npm run deploy:server
      - run:
          name: set environment variables to EB
          command: npm run setenv
workflows:
    main:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - master